name: weight_slider
description: Customisable slider widget for retrieving weight.
version: 1.0.0
homepage: https://covalsolutions.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - images/